// Auto-generated by scripts/generate-migrations-manifest.ts — do not edit.
export type MigrationEntry = {
  id: string;
  filename: string;
  sql: string;
};

export const MIGRATIONS: MigrationEntry[] = [
  {
    id: "001_create_faced_records",
    filename: "001_create_faced_records.sql",
    sql: "-- migration: 001_create_faced_records\r\nCREATE TABLE IF NOT EXISTS faced_records (\r\n  uuid TEXT PRIMARY KEY,\r\n  barangay TEXT NOT NULL,\r\n  city_municipality TEXT,\r\n  province TEXT,\r\n  date_registered TEXT,\r\n  payload TEXT NOT NULL,\r\n  created_at TEXT NOT NULL,\r\n  updated_at TEXT NOT NULL\r\n);\r\n\r\nCREATE INDEX IF NOT EXISTS idx_faced_barangay ON faced_records(barangay);\r\n\r\nCREATE INDEX IF NOT EXISTS idx_faced_province ON faced_records(province);\r\n",
  },
  {
    id: "002_add_enumerator_name",
    filename: "002_add_enumerator_name.sql",
    sql: "-- migration: 002_add_enumerator_name\r\nALTER TABLE faced_records ADD COLUMN enumerator_name TEXT NOT NULL DEFAULT '';\r\n\r\nCREATE INDEX IF NOT EXISTS idx_faced_enumerator ON faced_records(enumerator_name);\r\n",
  },
  {
    id: "003_create_access_codes",
    filename: "003_create_access_codes.sql",
    sql: "-- Access codes for enumerator login\r\nCREATE TABLE IF NOT EXISTS access_codes (\r\n  code TEXT PRIMARY KEY,\r\n  status TEXT NOT NULL DEFAULT 'active',\r\n  created_at TEXT NOT NULL,\r\n  rejected_at TEXT,\r\n  last_used_at TEXT\r\n);\r\n\r\nCREATE INDEX IF NOT EXISTS idx_access_codes_status ON access_codes(status);\r\n",
  },
  {
    id: "004_access_code_single_session",
    filename: "004_access_code_single_session.sql",
    sql: "-- Bind each code to a single device session (one-time use)\r\nALTER TABLE access_codes ADD COLUMN session_id TEXT;\r\nALTER TABLE access_codes ADD COLUMN used_at TEXT;\r\n",
  },
  {
    id: "005_access_code_enumerator",
    filename: "005_access_code_enumerator.sql",
    sql: "-- Track who each access code was assigned to\r\nALTER TABLE access_codes ADD COLUMN enumerator_name TEXT;\r\nALTER TABLE access_codes ADD COLUMN enumerator_email TEXT;\r\n",
  },
  {
    id: "006_faced_records_access_code",
    filename: "006_faced_records_access_code.sql",
    sql: "-- migration: 006_faced_records_access_code\r\nALTER TABLE faced_records ADD COLUMN access_code TEXT NOT NULL DEFAULT '';\r\n\r\nCREATE INDEX IF NOT EXISTS idx_faced_access_code ON faced_records(access_code);\r\n",
  },
  {
    id: "007_soft_delete_faced_records",
    filename: "007_soft_delete_faced_records.sql",
    sql: "-- migration: 007_soft_delete_faced_records\r\nALTER TABLE faced_records ADD COLUMN deleted_at TEXT;\r\n\r\nCREATE INDEX IF NOT EXISTS idx_faced_deleted_at ON faced_records(deleted_at);\r\n",
  },
  {
    id: "008_ec_library",
    filename: "008_ec_library.sql",
    sql: "-- Admin-managed evacuation center sites (per municipality + barangay)\r\nCREATE TABLE IF NOT EXISTS ec_library (\r\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\r\n  city_municipality TEXT NOT NULL,\r\n  barangay TEXT NOT NULL,\r\n  site_name TEXT NOT NULL,\r\n  created_at TEXT NOT NULL,\r\n  updated_at TEXT NOT NULL\r\n);\r\n\r\nCREATE INDEX IF NOT EXISTS idx_ec_library_location\r\n  ON ec_library(city_municipality, barangay);\r\n\r\nCREATE UNIQUE INDEX IF NOT EXISTS idx_ec_library_unique_site\r\n  ON ec_library(city_municipality, barangay, site_name);\r\n",
  },
  {
    id: "009_duplicate_pair_exclusions",
    filename: "009_duplicate_pair_exclusions.sql",
    sql: "-- Admin-verified pairs that share first+last name but are distinct families\r\nCREATE TABLE IF NOT EXISTS duplicate_pair_exclusions (\r\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\r\n  uuid_a TEXT NOT NULL,\r\n  uuid_b TEXT NOT NULL,\r\n  name_key TEXT NOT NULL,\r\n  excluded_at TEXT NOT NULL,\r\n  excluded_by TEXT NOT NULL DEFAULT 'admin',\r\n  note TEXT NOT NULL DEFAULT '',\r\n  UNIQUE(uuid_a, uuid_b)\r\n);\r\n\r\nCREATE INDEX IF NOT EXISTS idx_duplicate_pair_exclusions_name_key\r\n  ON duplicate_pair_exclusions(name_key);\r\n\r\nCREATE INDEX IF NOT EXISTS idx_duplicate_pair_exclusions_uuid_a\r\n  ON duplicate_pair_exclusions(uuid_a);\r\n\r\nCREATE INDEX IF NOT EXISTS idx_duplicate_pair_exclusions_uuid_b\r\n  ON duplicate_pair_exclusions(uuid_b);\r\n",
  },
  {
    id: "009_usability_survey",
    filename: "009_usability_survey.sql",
    sql: "-- Encoder feedback survey responses (replaces any legacy usability_survey table)\r\nDROP TABLE IF EXISTS usability_survey_responses;\r\n\r\nCREATE TABLE usability_survey_responses (\r\n  id INTEGER PRIMARY KEY AUTOINCREMENT,\r\n  name TEXT,\r\n  municipality TEXT NOT NULL,\r\n  payload TEXT NOT NULL,\r\n  created_at TEXT NOT NULL\r\n);\r\n\r\nCREATE INDEX IF NOT EXISTS idx_survey_responses_created_at\r\n  ON usability_survey_responses (created_at);\r\n\r\nCREATE INDEX IF NOT EXISTS idx_survey_responses_municipality\r\n  ON usability_survey_responses (municipality);\r\n",
  },
  {
    id: "010_batch_pdf_jobs",
    filename: "010_batch_pdf_jobs.sql",
    sql: "CREATE TABLE IF NOT EXISTS batch_pdf_jobs (\r\n  id TEXT PRIMARY KEY,\r\n  status TEXT NOT NULL,\r\n  logs TEXT NOT NULL DEFAULT '[]',\r\n  filename TEXT NOT NULL,\r\n  area_label TEXT NOT NULL,\r\n  record_count INTEGER NOT NULL,\r\n  token TEXT NOT NULL,\r\n  payload TEXT,\r\n  pdf_data BLOB,\r\n  chunk_index INTEGER NOT NULL DEFAULT 0,\r\n  error TEXT,\r\n  created_at TEXT NOT NULL,\r\n  updated_at TEXT NOT NULL\r\n);\r\n\r\nCREATE INDEX IF NOT EXISTS idx_batch_pdf_jobs_status ON batch_pdf_jobs (status, updated_at);\r\n",
  },
  {
    id: "011_family_assistance_records",
    filename: "011_family_assistance_records.sql",
    sql: "-- migration: 011_family_assistance_records\r\nCREATE TABLE IF NOT EXISTS family_assistance_record (\r\n  uuid TEXT PRIMARY KEY,\r\n  faced_record_uuid TEXT NOT NULL,\r\n  access_code TEXT NOT NULL DEFAULT '',\r\n  date_provided TEXT NOT NULL,\r\n  receiving_member_name TEXT NOT NULL,\r\n  assistance_received TEXT NOT NULL,\r\n  unit TEXT NOT NULL DEFAULT '',\r\n  quantity TEXT NOT NULL DEFAULT '',\r\n  provider TEXT NOT NULL DEFAULT '',\r\n  created_at TEXT NOT NULL,\r\n  updated_at TEXT NOT NULL\r\n);\r\n\r\nCREATE INDEX IF NOT EXISTS idx_family_assistance_faced_uuid\r\n  ON family_assistance_record(faced_record_uuid);\r\n\r\nCREATE INDEX IF NOT EXISTS idx_family_assistance_date\r\n  ON family_assistance_record(date_provided);\r\n",
  },
  {
    id: "012_cost_of_assistance",
    filename: "012_cost_of_assistance.sql",
    sql: "-- migration: 012_cost_of_assistance\r\nALTER TABLE family_assistance_record\r\n  ADD COLUMN cost_of_assistance TEXT NOT NULL DEFAULT '';\r\n",
  },
];
