import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const migrationsDir = join(process.cwd(), "migrations");
const outPath = join(process.cwd(), "src/lib/migrations-manifest.ts");

const files = readdirSync(migrationsDir)
  .filter((f) => f.endsWith(".sql"))
  .sort();

const entries = files.map((filename) => {
  const id = filename.replace(/\.sql$/, "");
  const sql = readFileSync(join(migrationsDir, filename), "utf8");
  return { id, filename, sql };
});

const body = entries
  .map(
    ({ id, filename, sql }) =>
      `  {\n    id: ${JSON.stringify(id)},\n    filename: ${JSON.stringify(filename)},\n    sql: ${JSON.stringify(sql)},\n  }`,
  )
  .join(",\n");

const output = `// Auto-generated by scripts/generate-migrations-manifest.ts — do not edit.
export type MigrationEntry = {
  id: string;
  filename: string;
  sql: string;
};

export const MIGRATIONS: MigrationEntry[] = [
${body},
];
`;

writeFileSync(outPath, output, "utf8");
console.log(`Wrote ${entries.length} migration(s) to ${outPath}`);
